### ISSUE TITLE
README example for lettrine look strange?

### ISSUE THREAD

**Issue by bjornbm** [tomduck/pandoc-latex-extensions#3]
Is the example correct? And if so, does the extension work as intended? (The text `ipsum dolor sit amet,` is not included in the output.)

**Comment by tomduck** [comment]
Thanks for this bug report.  This is a very new filter, and I appreciate your contributions.

It turns out that the lettrine package only applies to the first word.  I fixed the filter, and ensured that nothing is dropped if more than one word appears in the span.

--Tom
